import { useEffect, useState } from 'react';
import {
  approveMaterial,
  exportMaterialMarkdown,
  fetchMaterial,
  generateMaterial,
  requestMaterialChanges,
  type CurriculumMaterial,
} from '../api/agents';
import MarkdownRenderer from '../components/MarkdownRenderer';

function statusLabel(status: CurriculumMaterial['approval_status']) {
  if (status === 'approved') return 'Approved';
  if (status === 'needs_changes') return 'Needs changes';
  return 'Pending approval';
}

export default function MaterialPreview() {
  const [material, setMaterial] = useState<CurriculumMaterial | null>(null);
  const [prompt, setPrompt] = useState('');
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    const data = await fetchMaterial();
    setMaterial(data);
    setLoading(false);
  }

  useEffect(() => {
    void load();
    function refresh() {
      void load();
    }
    window.addEventListener('curriculum:changed', refresh);
    return () => window.removeEventListener('curriculum:changed', refresh);
  }, []);

  async function handleGenerate() {
    setWorking(true);
    setError(null);
    const data = await generateMaterial(material ? {
      lab_id: material.lab_id,
      course_id: material.course_id,
      title: material.title,
      learning_objectives: material.learning_objectives,
      difficulty: material.difficulty,
      estimated_duration_min: material.estimated_duration_min,
    } : undefined);
    if (data) {
      setMaterial(data);
      window.dispatchEvent(new CustomEvent('curriculum:changed'));
    } else {
      setError('Could not generate material. Check that Orchestrator and Curriculum Designer are running.');
    }
    setWorking(false);
  }

  async function handleApprove() {
    if (!material) return;
    setWorking(true);
    setError(null);
    const data = await approveMaterial(material.lab_id);
    if (data) {
      setMaterial(data);
      window.dispatchEvent(new CustomEvent('curriculum:changed'));
    } else {
      setError('Could not approve material. Check the backend logs for details.');
    }
    setWorking(false);
  }

  async function handleRequestChanges() {
    const feedback = prompt.trim();
    if (!feedback || !material) return;
    setWorking(true);
    setError(null);
    const data = await requestMaterialChanges(feedback, material.lab_id);
    if (data) {
      setMaterial(data);
      setPrompt('');
      window.dispatchEvent(new CustomEvent('curriculum:changed'));
    } else {
      setError('Could not request changes. Make sure a draft exists and the backend is healthy.');
    }
    setWorking(false);
  }

  const approved = material?.approval_status === 'approved';

  return (
    <div className="content-card">
      <div className="content-header">
        <div className="content-title">
          <h2>{material ? `${material.lab_id} - ${material.title} Tasks` : 'Lab Tasks'}</h2>
          <p>
            {material
              ? `Version ${material.version} · Generated by AI · ${statusLabel(material.approval_status)}`
              : 'No curriculum draft loaded'}
          </p>
        </div>
        <div className="content-actions">
          <button className="btn-outline" onClick={handleGenerate} disabled={working}>
            {working ? 'Generating...' : material ? 'Regenerate Draft' : 'Generate Lab Tasks'}
          </button>
          <button className="btn-outline" onClick={() => material && exportMaterialMarkdown(material)} disabled={!material}>
            Export
          </button>
          <div className="content-actions-divider" />
          <button className="btn-approve" onClick={handleApprove} disabled={!material || approved || working}>
            {approved ? 'Approved' : 'Approve'}
          </button>
        </div>
      </div>

      <hr className="content-divider" />

      {loading && <div className="empty-state">Loading curriculum material...</div>}

      {!loading && error && <div className="error-state">{error}</div>}

      {!loading && !material && (
        <div className="empty-state">
          No generated lab material yet. Generate a draft to start the pre-lab workflow.
        </div>
      )}

      {!loading && material && (
        <>
          <div className="material-meta-row">
            <span className={`material-status material-status-${material.approval_status}`}>
              {statusLabel(material.approval_status)}
            </span>
            <span>{material.estimated_duration_min} min</span>
            <span>{material.difficulty}</span>
            <span>{material.learning_objectives.length} objectives</span>
          </div>
          <div className="material-markdown">
            <MarkdownRenderer markdown={material.spec_markdown} />
          </div>
        </>
      )}

      <div className="prompt-input-bar">
        <input
          type="text"
          placeholder='Ask the agent to refine this content...  e.g. "Make deletion edge cases clearer"'
          value={prompt}
          onChange={e => setPrompt(e.target.value)}
          disabled={!material || working}
        />
        <button className="btn-send" onClick={handleRequestChanges} disabled={!material || !prompt.trim() || working}>
          Send
        </button>
      </div>
    </div>
  );
}
